### PR TITLE
Updated condition in normal mode

### PR DESCRIPTION
**Pull request by abhijitgawai**

### CODE REVIEW

**Comment by abhijitgawai** [comment]
@danielattilasimon Can you please check this PR

**Comment by danielattilasimon** [comment]
During normal mode, no exception is made for Troves below 100% collateralization. That only happens during recovery mode.

**Comment by abhijitgawai** [comment]
So, 

> You are Redistributing Coll+Debt Using DefaultPool, 

****OR****  

> Offseting Debt Using LUSD from Stability Pool (In this case StabilityPool depositors will be at loss)

**Comment by danielattilasimon** [comment]
Yes.

In normal mode, the priority is to offset debt using the Stability Pool, even if it's at a loss to depositors. The chance of it being a loss is very small though: the Trove would have to go unliquidated long enough for ETH to drop by ~10%.

When the Stability Pool gets empty, the coll/debt is redistributed instead.

https://github.com/liquity/dev/blob/448b1799dea8c288f91cdaf12b55a19ed459173d/packages/contracts/contracts/TroveManager.sol#L442-L451

**Pull request closed without merging**
