### PR TITLE
fix(.gitattributes): prevent github from showing json comments as errors

### PR DESCRIPTION
**Pull request by Alexangelj**
Example:

image

### CODE REVIEW

**Comment by bingen** [comment]
As far as I know, comments are not standard in JSON. See for instance: https://stackoverflow.com/a/4183018 or https://web.archive.org/web/20150105080225if_/https://plus.google.com/+DouglasCrockfordEsq/posts/RK8qyGVaGSr
Do we have any commented JSON files in our codebase? That example you showed doesn’t look familiar to me.

**Comment by Alexangelj** [comment]
Yes the default config file for api-extractor has comments here: https://github.com/liquity/dev/blob/main/api-extractor.base.json

The api-extractor package has a blob in their docs explaining why they have JSON comments: https://api-extractor.com/pages/setup/invoking/

**Comment by bingen** [comment]
Oh, I see, you are right! I guess it makes sense then, but I’ll let @danielattilasimon review it.
Thanks!

**Review by danielattilasimon — APPROVED** [review]
Thanks, looks good! 👍

I never viewed this file on GitHub before, wasn't aware of the highlighting.

**Pull request merged**
